apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-router
  template:
    metadata:
      labels:
        app: nginx-router
    spec:
      containers:
        - name: nginx-router
          image: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-config
            - mountPath: /etc/nginx/certs
              name: c4e-ssl
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: c4e-ssl
          secret:
            secretName: c4e-ssl
