apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-router
  labels:
    app: nginx-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-router
  template:
    metadata:
      labels:
        app: nginx-router
    spec:
#      initContainers:
#        - name: images
#          image: busybox:1.28
#          command: [ "/bin/sh","-c", "sleep 10" ]
#          volumeMounts:
#            - name: images
#              mountPath: "/assets"
      containers:
        - name: nginx-router
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: np-config
            - mountPath: /etc/nginx/certs
              name: c4e-ssl
              readOnly: true
            - mountPath: /app/landingPage.html
              name: landing-page
              subPath: landingPage.html
            - mountPath: /assets/
              name: images
      volumes:
        - name: np-config
          configMap:
            name: np-config
        - name: c4e-ssl
          secret:
            secretName: c4e-ssl
        - name: landing-page
          configMap:
            name: landing-page
        - name: images
          persistentVolumeClaim:
            claimName: ec-nginx-router-docs