apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-proxy
  name: nginx-proxy
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
