apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-router
  name: nginx-router
  namespace: nginx-proxy
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32732
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-router
  sessionAffinity: None
  type: NodePort
