apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-ssr
  labels:
    app: nuxt-ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-ssr
  template:
    metadata:
      labels:
        app: nuxt-ssr
    spec:
      containers:
        - name: nuxt-ssr
          image: 10.0.8.1:5000/nuxt-ssr  # Obraz lokalny
          imagePullPolicy: Always         # Kubernetes nie próbuje ściągać obrazu z rejestru
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
