apiVersion: v1
kind: PersistentVolume
metadata:
  name: nuxt-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ovoo-ssd  # This must match your PVC!
  hostPath:
    path: "/data/nuxt-app"  # Adjust this to your actual storage location
