apiVersion: v1
kind: Service
metadata:
  name: nuxt-ssr-service
  labels:
    app: nuxt-ssr
spec:
  selector:
    app: nuxt-ssr
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
