kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ec-nginx-router-docs
spec:
  storageClassName: ovoo-ssd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi