apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-router
  name: nginx-router
  namespace: nginx-proxy
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.233.12.96
  clusterIPs:
    - 10.233.12.96
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31216
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx-router
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.0.14.79