bases:
  - ../../base
namespace: soe-prod
images:
  - name: nginx-proxy
    newName: g99vzm03.gra7.container-registry.ovh.net/c4e/nginx-proxy
    newTag: prod-1.0.18
patchesStrategicMerge:
  - ui-regcred.yaml
  - ui-affinity.yaml
  - nginx-proxy-config.yaml
  - ui-deployment_secret.yaml